title: PQYandexMetrica
description: Коннектор к Reporting API Яндекс.Метрики для Power BI и Excel (через Power Query)
google_analytics: 
google:
  tag_manager:
    container_id: GTM-TL5F562
show_downloads: false
theme: jekyll-theme-minimal

plugins:
  - jekyll-mentions
