title: PQYandexMetrica
description: Коннектор к Reporting API Яндекс.Метрики для Power BI и Excel (через Power Query)
google_analytics: 
gtm: GTM-TL5F562
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
