theme: jekyll-theme-slate
google_analytics: UA-135774507-1
title: PQYandexMetrica
description: Неофициальный, открытый коннектор для выгрузки данных из Reporting API Яндекс.Метрики в Power BI и Excel, скрипт на языке Power Query
lang: ru-RU
facebook:
  app_id: 319015628771849
  admins: maxim.uvarov
plugins:  
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap

